apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fuoz5018d-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fuoz5018d-java-springboot-gitops